package com.app.currents.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.app.currents.ui.theme.Accent
import com.app.currents.ui.theme.CurrentsIcons
import com.app.currents.ui.theme.CurrentsTheme
import org.jetbrains.compose.resources.painterResource

@Composable
fun AISummaryCard(
    summary: String,
    isLoading: Boolean = false,
    modifier: Modifier = Modifier,
) {
    val borderColor = Accent

    Column(
        modifier = modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(12.dp))
            .background(MaterialTheme.colorScheme.surfaceVariant)
            .drawBehind {
                // Purple left border
                drawLine(
                    color = borderColor,
                    start = Offset(0f, 0f),
                    end = Offset(0f, size.height),
                    strokeWidth = 3.dp.toPx(),
                )
            }
            .padding(start = 16.dp, end = 16.dp, top = 12.dp, bottom = 12.dp),
        verticalArrangement = Arrangement.spacedBy(8.dp),
    ) {
        // Header — spark icon + AI SUMMARY label
        Row(
            horizontalArrangement = Arrangement.spacedBy(6.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Icon(
                painter = painterResource(CurrentsIcons.Spark),
                contentDescription = null,
                tint = Accent,
                modifier = Modifier.size(14.dp),
            )
            Text(
                text = "AI SUMMARY",
                color = Accent,
                fontSize = 11.sp,
                fontWeight = FontWeight.Bold,
                letterSpacing = 0.8.sp,
            )
        }

        // Summary text
        if (isLoading) {
            Text(
                text = "Generating summary...",
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                fontSize = 14.sp,
                lineHeight = 22.sp,
            )
        } else {
            Text(
                text = summary,
                color = MaterialTheme.colorScheme.onSurface,
                fontSize = 14.sp,
                lineHeight = 22.sp,
                fontWeight = FontWeight.Normal,
            )
        }

        // Generated by caption
        Text(
            text = "Generated by Currents AI",
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            fontSize = 11.sp,
            fontWeight = FontWeight.Normal,
            textAlign = TextAlign.End,
            modifier = Modifier.fillMaxWidth(),
        )
    }
}

@Preview
@Composable
private fun AISummaryCardDarkPreview() {
    CurrentsTheme(darkTheme = true) {
        AISummaryCard(
            summary = "Nearly 200 nations agreed to triple renewable capacity by 2035 and phase down coal. The deal includes a \$100B fund for developing economies and binding five-year reviews.",
        )
    }
}

@Preview
@Composable
private fun AISummaryCardLoadingDarkPreview() {
    CurrentsTheme(darkTheme = true) {
        AISummaryCard(
            summary = "",
            isLoading = true,
        )
    }
}

@Preview
@Composable
private fun AISummaryCardLightPreview() {
    CurrentsTheme(darkTheme = false) {
        AISummaryCard(
            summary = "Nearly 200 nations agreed to triple renewable capacity by 2035 and phase down coal. The deal includes a \$100B fund for developing economies and binding five-year reviews.",
        )
    }
}